title: Books & Highlights
email: alessandro.ferrari.2004@gmail.com
description: >-
  This is a collection of my highlights for books that I've read.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://books.alessandroferrari.live/"
twitter_username: BioAlessandro
github_username: Ferryistaken

plugins:
  - jekyll-feed

collections:
  books:
    output: true

sass:
  style: compressed
